#!/usr/bin/env bash
# Secure copy from the client to a server
if [ $# -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa some_page.html ubuntu@54.237.4.27:~
fi

